permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:

      ####################################################
      # Checkout Code
      ####################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ####################################################
      # Setup Terraform
      ####################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      ####################################################
      # Configure AWS Using OIDC
      ####################################################

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::986401823783:role/bpay-etl-githubaction-role
          aws-region: ap-south-1

      ####################################################
      # Verify AWS Login
      ####################################################

      - name: Verify AWS Login
        run: |
          aws sts get-caller-identity

      ####################################################
      # Debug Repository
      ####################################################

      - name: Debug Repository
        run: |
          echo "Repository=${{ github.repository }}"
          echo "Ref=${{ github.ref }}"

      ####################################################
      # Create PEM File
      ####################################################

      - name: Create EC2 PEM File
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > bastion-key.pem
          chmod 400 bastion-key.pem

      ####################################################
      # Terraform Init
      ####################################################

      - name: Terraform Init
        run: |
          terraform init

      ####################################################
      # Terraform Validate
      ####################################################

      - name: Terraform Validate
        run: |
          terraform validate

      ####################################################
      # Terraform Plan
      ####################################################

      - name: Terraform Plan
        run: |
          terraform plan

      ####################################################
      # Terraform Apply
      ####################################################

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve